import type { PortfolioAnalysisResponse } from '../src/features/portfolio/types';
export const user = { id: '11111111-1111-4111-8111-111111111111', email: 'demo@example.com' };
export const report: PortfolioAnalysisResponse = {
  id: '22222222-2222-4222-8222-222222222222',
  created_at: '2026-09-10T12:00:00Z',
  positions: [
    { ticker: 'QQQ', allocation: 60, average_price: 500 },
    { ticker: 'VTI', allocation: 40, average_price: 250 },
  ],
  analysis: {
    method: 'etf-v1',
    concentration: 52,
    effective_positions: 1.92,
    largest_allocation: 60,
    position_count: 2,
    observations: ['QQQ is the largest position at 60%.', 'Stored ETF data covers 60%.'],
    data_coverage: 60,
    etfs: [
      {
        ticker: 'QQQ',
        status: 'available',
        message: 'Stored ETF data is current.',
        snapshot_id: '33333333-3333-4333-8333-333333333333',
        source: 'alpha-vantage',
        as_of: '2026-09-10T20:00:00Z',
        currency: 'USD',
        current_price: 600,
        price_change: 20,
        expense_ratio: 0.2,
        holdings_coverage: 18.65,
        top_holdings: [{ name: 'NVIDIA Corp', fund_weight: 9.8, portfolio_exposure: 5.88 }],
      },
      {
        ticker: 'VTI',
        status: 'unavailable',
        message: 'No stored ETF data is available and live data is not configured.',
        snapshot_id: null,
        source: null,
        as_of: null,
        currency: null,
        current_price: null,
        price_change: null,
        expense_ratio: null,
        holdings_coverage: null,
        top_holdings: [],
      },
    ],
    underlying_exposure: [{ name: 'NVIDIA Corp', portfolio_exposure: 5.88 }],
  },
};
